CREATE TABLE PUSH_COUNTS AS
SELECT
    repo_name,
    COUNT(*) AS push_count,
    WINDOWSTART AS window_start
FROM GITHUB_PUSH_STREAM_NEW
WINDOW TUMBLING (SIZE 5 MINUTES)
GROUP BY repo_name
EMIT CHANGES;
